on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate OpenAPI
        run: python manage.py export_openapi_schema --api config.urls.api > open-api.json
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Parse To HTML
        run: |
          npm install -g redoc-cli
          redoc-cli bundle open-api.json -o .${{ github.ref_name }}/index.html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .${{ github.ref_name }}
  deploy:
    # https://docs.github.com/ja/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}${{ github.ref_name }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ github.ref_name }}
          folder: .${{ github.ref_name }}
          clean: false
