on: [push]

env:
  API: 'https://api.github.com/repos/takap-sandbox/django-ninja-openapi-ci/actions/workflows/test.yml/runs?status=success'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      SAFE_REF_NAME: ${{ steps.safe-url.outputs.SAFE_REF_NAME }}
    steps:
      - name: Convert Branch Name To Safe Url
        id: safe-url
        run: |
          SAFE_REF_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-' | tr -d '#')
          echo "SAFE_REF_NAME=${SAFE_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Fetch Prev Run Id
        run: |
          RUN_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{env.API}} | jq -r '.workflow_runs[0] | select(.name == ".github/workflows/test.yml") | .id')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
      - name: Download Prev Artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: output-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ env.RUN_ID }}
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate OpenAPI
        run: python manage.py export_openapi_schema --api config.urls.api > open-api.json
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Parse To HTML
        run: |
          npm install -g redoc-cli
          redoc-cli bundle open-api.json -o .output/${{ steps.safe-url.outputs.SAFE_REF_NAME }}/index.html
        continue-on-error: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-artifact
          path: .output/
          compression-level: 0
          include-hidden-files: true
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output
  deploy:
    # https://docs.github.com/ja/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}${{ needs.build.outputs.SAFE_REF_NAME }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
