on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Convert Branch Name To Safe Url
        run: |
          SAFE_REF_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-' | tr -d '#')
          echo "SAFE_REF_NAME=${SAFE_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Restore cached
        id: cache-output-restore
        uses: actions/cache/restore@v4
        with:
          path: .output
          key: openapi-output
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate OpenAPI
        run: python manage.py export_openapi_schema --api config.urls.api > open-api.json
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Parse To HTML
        run: |
          npm install -g redoc-cli
          redoc-cli bundle open-api.json -o .output/${{ env.SAFE_REF_NAME }}/index.html
      - name: Save Output
        id: cache-output-save
        uses: actions/cache/save@v4
        with:
          path: .output
          key: openapi-output
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output
  deploy:
    # https://docs.github.com/ja/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}${{ env.SAFE_REF_NAME }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
